apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.releaseName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}
    spec:
      containers:
        - name: {{ .Values.releaseName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
