replicaCount: 1

releaseName: auth-release          # Use this to name deployment and service
namespace: auth-namespace          # Kubernetes namespace

image:
  repository: kuunyangna/auth-controller
  tag: latest

service:
  name: auth-service-svc
  type: LoadBalancer
  port: 80           # External port
  targetPort: 8080   # Container port

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
